name: daily Intensivregister

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: download Intensivregister
        run: cd .github/workflows/ && env python3 ./download_Intensivregister.py && cd ../../
      - name: compress Intesivregister dump
        run: |
          gzip -f ./Intensivregister/raw_data/bundesland-zeitreihe_*.csv | tee >> ./Intensivregister/raw_data/bundesland-zeitreihe_latest.csv.gz
          gzip -f ./Intensivregister/raw_data/DIVI_Intensivregister_Auszug_pro_Landkreis_*.csv | tee >> ./Intensivregister/raw_data/DIVI_Intensivregister_Auszug_pro_Landkreis_latest.csv.gz
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./Intensivregister/raw_data/*.csv.gz
          git commit -m "daily update Intensivregister"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
