name: daily RKI update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: download RKI dump
        run: cd .github/workflows/ && env python3 ./download_RKI_COVID19.py
        
