name: daily Nowcasting

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: download Nowcasting
        run: cd .github/workflows/ && env python3 ./download_Nowcasting.py && cd ../../
      - name: compress Nowcasting dump
        run: |
          gzip -f ./Nowcasting/raw_data/*.csv | tee >> ./Nowcasting/raw_data/Nowcasting_Zahlen_csv_latest.csv.gz
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./Intensivregister/raw_data/*.csv.gz
          git commit -m "daily update Nowcasting"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
