name: daily Impfquotenmonitoring update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: update apt
        run: sudo apt-get update
      - name: Install gnuplot
        run: sudo apt-get install gnuplot
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl
      - name: download RKI Impfquotenmonitoring
        run: cd .github/workflows/ && env python3 ./download_RKI_Impfquotenmonitoring.py && cd ../../
      - name: run gnuplot
        run: cd Impfquotenmonitoring/gnuplot/ && chmod +x ./generate_plots.sh && ./generate_plots.sh && cd ../../
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./Impfquotenmonitoring/*.xlsx ./Impfquotenmonitoring/*.csv ./Impfquotenmonitoring/gnuplot/*.png
          git commit -m "daily Impfquotenmonitoring update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
        
