name: daily RKI update

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
  schedule:
    - cron: "30 14 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: download RKI dump
        run: cd .github/workflows/ && env python3 ./download_RKI_COVID19.py && cd ../../
      - name: copy RKI dump to _latest file
        run: cp *.csv RKI_COVID19_latest.csv
      - name: compress RKI dump
        run: gzip *.csv
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./*.csv.gz
          git commit -m "daily update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
        
